---
- name: Install and configure Grafana on Amazon Linux 2
  hosts: all
  become: yes

  tasks:
    - name: Install required dependencies
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - fontconfig
        - freetype*

    - name: Add Grafana repository
      get_url:
        url: https://rpm.grafana.com/grafana.repo
        dest: /etc/yum.repos.d/grafana.repo

    - name: Install Grafana
      yum:
        name: grafana
        state: present

    - name: Enable and start Grafana service
      systemd:
        name: grafana-server
        enabled: yes
        state: started
